name: VersionModifier
version: 2.0
author: applqpak
authors: [applqpak, IceCruelStuff]
api: 3.14.0
main: VersionModifier\Main
commands:
  enableversion:
    description: Enables customized version
    permission: version.enable
    aliases: [enablever]

  disableversion:
    description: Disables customized version
    permission: version.disable
    aliases: [disablever]

permissions:
  version.enable:
    description: Allows user to use /enableversion
    default: op

  version.disable:
    description: Allows user to use /disableversion
    default: op
